services:
  api:
    container_name: docket_apiserver
    image: docket:v1
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
      - RUN_MIGRATIONS=true
    depends_on:
      - mysql
  mysql:
    container_name: docket_mysql
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cunningpassword
      - MYSQL_DATABASE=docket_local
      - MYSQL_USER=go
      - MYSQL_PASSWORD=password
      - MYSQL_ONETIME_PASSWORD=false
    volumes:
      - ./db_data:/var/lib/mysql
